"""Add album owner

Revision ID: 2aab71d88382
Revises: 
Create Date: 2025-05-16 18:35:49.078492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aab71d88382'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albuns', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'albuns', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albuns', type_='foreignkey')
    op.drop_column('albuns', 'owner_id')
    # ### end Alembic commands ###
