"""database

Revision ID: 3647532541dd
Revises: 
Create Date: 2025-08-01 20:47:18.027500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3647532541dd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albuns', 'passcode')
    op.drop_column('albuns', 'owner_id')
    op.drop_column('albuns', 'publico')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albuns', sa.Column('publico', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('albuns', sa.Column('owner_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('albuns', sa.Column('passcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
