"""Added Image height and width

Revision ID: 695746f0340e
Revises: 2aab71d88382
Create Date: 2025-05-23 21:19:17.042941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695746f0340e'
down_revision: Union[str, None] = '2aab71d88382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagens', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('imagens', sa.Column('height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imagens', 'height')
    op.drop_column('imagens', 'width')
    # ### end Alembic commands ###
