services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_container
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/app
      - ./api/imagens:/app/imagens
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db
      - redis
  db:
    image: postgres:13
    container_name: postgres_container
    env_file:
      - ./api/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:6
    container_name: redis_container
    ports:
      - "6379:6379"
volumes:
  postgres_data: